### ISSUE TITLE
Layout for keyboards with 30 non-thumb keys?

### ISSUE THREAD

**Issue by mekeor** [dariogoetz/noted-layout#11]
Hello! I will soon have a minimalist keyboard with 30 non-thumb keys, like this:

```
| a | b | c | d | e |     | f | g | h | i | j |
| k | l | m | n | o |     | p | q | r | s | t |
| u | v | w | x | y |     | z | ä | ö | u | ß |

        | ? | ? | ? |     | ? | ? | ? |
```

I wonder if you could recommend any layout for this situation. I would prefer to put the dot- and comma-keys on higher layers and thus keep all letters on the main, default layer.

Compared to Noted-layout for crkbd/cantor-style keyboards, we would need to remove the dot- and comma-keys and move the j- and ß-keys.

**Comment by dariogoetz** [comment]
You could try noted (crkbd/cantor-style) and put `j` and `ß` on the dot and comma positions, as you suggest. Or put `j` and `ß` on long-press on some other key, preserving dot and comma on the base layer.

If you like a more "personalized" layout, you can try playing around with the [layout evaluator](https://github.com/dariogoetz/keyboard_layout_optimizer) that was used to generate the `noted` layout. Apart from that, I don't have a specific layout to recommend for such a small layout.
