### ISSUE TITLE
MOD4-Navigation keys not working

### ISSUE THREAD

**Issue by MaxG87** [dariogoetz/noted-layout#2]
I learned about this layout on the mailing list. It looks very promising. I especially like the weighting of German and English, as this matches my daily typing experiences very good. Thank you very much.

I wanted to give it a try and were able to activate the layout. What I quickly noticed is that the arrow keys in layer 4 are not working for me. I would have expected that only the letters change in comparison to Neo2. Is this a bug with my system or something due to the layout?

I am running Debian stable.

**Comment by dariogoetz** [comment]
Recently, there was a refactoring in xkeyboard-config that had an impact on the Neo layouts. I guess that the xkeyboard-config that Debian stable is running is <2.39.

I have added another config file for pre-2.39 versions here: https://raw.githubusercontent.com/dariogoetz/noted-layout/main/xkb/noted_pre239

You would need to rename this file to `noted` when copying it to the xkeyboard-config directory.

**Comment by MaxG87** [comment]
Klappt! Thank you very much.
