### ISSUE TITLE
Appreciation

### ISSUE THREAD

**Issue by ja0nz** [dariogoetz/noted-layout#3]
As a looong time neo typist I just came by to say thanks. I have seen a lot of layouts over the years but this one is the first time I feel has some completeness and cohesiveness. So this time I'll bite the bullet and switch for good - something I hope to achieve over this summer.

Feel free to close the issue right away😎

**Comment by dariogoetz** [comment]
I am very glad to hear that. Thank you very much :)

I hope that the layout is able to fulfill your expectations and wish you much fun and success in learning it :)

I would be happy to hear how it is going for you at some later point in time.
