### ISSUE TITLE
Why isn't N under the index finger anymore?

### ISSUE THREAD

**Issue by MaxG87** [dariogoetz/noted-layout#5]
Hi,

thank you very much for the new layout. I am about to learn it.

I wondered why the second most frequent letter is not located under the right index finger anymore. It seemed a very desirable property  for an ergonomic keyboard. After all, `e` still is under an index finger.

I am aware that the layout is the result of a highly complex automatic optimisation. So, maybe there isn't a intuitive explanation here. But in case there is, I would be very curious to learn about it.

**Comment by dariogoetz** [comment]
Hi Max, I am glad that you give the layout a try. I hope that it will work out well for you.

Given the rest of the layout, the main reason (besides a slightly more even distribution of weight across the fingers) is the locations of other keys on the right hand that often come directly before or after the `n`:
- `ng` is very nice to type with `n` on the middle finger and would be quite bad on the index finger
- `nd` is acceptable (certainly not perfect) with `n` on the middle and very bad with `n` on the index

Generally speaking: The index fingers cover six symbols, each, so these six symbol ideally are symbols that rarely appear next to each other. That property works better with the `t` than with the `n` for the given set of symbols on the right index finger. 

If one would like to have `n` and `t` reversed, one would also need to choose the other index-finger symbols differently, eventually ending up with a very different layout.

**Comment by MaxG87** [comment]
Thank you very much! This helps a lot to understand this decision.
