### ISSUE TITLE
Mod3 on left capslock

### ISSUE THREAD

**Issue by LeHarry** [dariogoetz/noted-layout#7]
Thank you very much for this awesome layout, I use it since 3 months now and it feels fresh. Quite the improvement to Neo2. Especially those points, next to the speed improvement:

- right Mod3 has been moved 1 to the left
- üäö moved out of the way
- cmd + z,y,c,v,x on the left is awesome

Issue: I bought a glorious XPS 17 with Ubuntu, it insists on the left capslock being a capslock instead of a Mod3. I installed Noted as per manual:

`Alternativ lässt sich hier: (https://dl.neo-layout.org/custom_noted) eine Variante herunterladen, die man unter dem Namen custom in den Pfad /usr/share/X11/xkb/symbols/ kopiert und mit setxkbmap custom aktiviert. Dies hat den Vorteil, dass es in den graphischen Einstellungen des jeweiligen Desktops eingestellt werden kann und bei Systemupdates nicht überschrieben wird.`

![grafik](https://github.com/dariogoetz/noted-layout/assets/160015230/b6006c40-5fb8-4cbf-b9af-75685d3e9cf4)

**Comment by dariogoetz** [comment]
Which version of xkeyboard-config are you running? Starting with version 2.39,some rule naming have changed and a different file version is required. You can find both versions on the neo homepage and here in the github files.

**Comment by LeHarry** [comment]
I am running **xkeyboard-config v 2.33** with the suggested **custom_noted** file on the main website.

**Comment by dariogoetz** [comment]
I assume, that you renamed the file to `custom`? Do you activate the layout via a GUI or via the commandline `setxkbmap custom`? If you are using a GUI, the corresponding program might add/overwrite other options to the layout definition. Does it work if you use the commandline?

**Comment by LeHarry** [comment]
Installation routine:

// rename to `"custom"`
// move to `/usr/share/X11/xkb/symbols`
// `$ setxkbmap custom`
![grafik](https://github.com/dariogoetz/noted-layout/assets/160015230/0fd7306f-94a8-46e0-8daa-9b865caeafde)

// no info tray to switch layouts
![grafik](https://github.com/dariogoetz/noted-layout/assets/160015230/4acc3352-3257-41d1-8b2b-603700138e5e)

// open layout manager, just move the layout up and back down once
![grafik](https://github.com/dariogoetz/noted-layout/assets/160015230/f3899995-0303-4e3a-8db0-9d05914660a7)

// now the info tray is visible
![grafik](https://github.com/dariogoetz/noted-layout/assets/160015230/fbd3f9da-eb79-4f35-81e6-51f67fac10b4)

// layout on every desktop machine
![grafik](https://github.com/dariogoetz/noted-layout/assets/160015230/2550f707-c46b-4241-a9fb-12c613d2e415)

// layout on the Notebook 'Dell XPS 9700'

**Comment by dariogoetz** [comment]
The "missing" Mod4 and Mod3-keys are less an issue of "high-end" notebooks, but rather due to the international "QWERTY" layout (instead of the German "QWERTZ" - note the change of Y and Z).

Also, I suspect that the fact that the CapsLock is not registered as Mod3 is not an hardware issue, but lies in the settings. Have you had a look at what is un-/checked in the "Optionen..." section (the button on the lower right). Do you see anything regarding CapsLock behavior there?

**Comment by LeHarry** [comment]
Oh damn really, that never crossed my sight. I guess those other keyboards I use were not originally designed for querty.
Well that resolved the issue - I checked and unchecked the `Feststelltaste` under options. Despite it being unchecked again capslock is now MOD3. Is this a bug?
![grafik](https://github.com/dariogoetz/noted-layout/assets/160015230/d41e68da-406d-42c5-9241-f4cc90dd1a1f)
