### ISSUE TITLE
Pasting using Ctrl-V does not work

### ISSUE THREAD

**Issue by MaxG87** [dariogoetz/noted-layout#9]
On both Debian Testing and Debian Stable (pre-2.39) I cannot paste text using Ctrl-V. I can do so using Shift-Insert, but that is a bit more inconvenient.

**Comment by dariogoetz** [comment]
I failed to reproduce the issue on a fresh Debian Testing installation in a Virtualbox (see also issue #8). Ctrl-C and Ctrl-V work just fine there.

Maybe your desktop environment (GNOME/KDE/...) is doing something behind the scenes? What desktop environment or window manager are you using?

**Comment by MaxG87** [comment]
While the issue described in #8 could not be reproduced on another machine, this one can.

On Debian Testing, using KDE 5.X on X11 from the normal repositories, Ctrl-V does not work using [this layout file](https://github.com/dariogoetz/noted-layout/blob/main/xkb/noted).

**Comment by dariogoetz** [comment]
The issue indeed seems to be an KDE global hotkey. Please try the following if it can resolve the issue for you:

There is a file called `~/.config/kglobalshortcutsrc`. In it, you should find an entry
```
[kded5]
Show System Activity=Ctrl+Esc,none,Systemaktivität anzeigen
```
(or similarly with your language)

Replace the `Ctrl+Esc` by `none` and then reload KDE or restart KDE's global hotkey service with `kquitapp5 kglobalaccel && sleep 2s && kglobalaccel5 &`. Then `Ctrl+V` should work again.

I guess that under the hood, `xkb` does something using `Escape` when doing its multi-level modifier magic for the `neo` families layouts.

**Comment by MaxG87** [comment]
Amazing! Thank you to find that out.

I fixed it by going through KDE's settings. I removed the shortcut ("Kurzbefehl") of KDE Daemon in the corresponding subpage.

Would you welcome if I contributed a troubleshooting section to the README?

**Comment by dariogoetz** [comment]
I surely would, thank you :)
